export const searchByAddressEvent = [
    { label: 'Đà Nẵng',id:1},
    { label: 'Bình Dương',id:2},
    { label: 'Bình Phước',id:3},
    
  ];
  export const searchByAddressBrand = [
    { label: 'An Giang',id : 1},
    { label: 'Bà rịa – Vũng tàu',id : 2},
    { label: 'Bắc Giang',id : 3},
    { label: 'Bắc Kạn',id : 4},
    { label: 'Bạc Liêu',id : 5},
    { label: 'Bắc Ninh',id : 6},
    { label: 'Bến Tre',id : 7},
    { label: 'Bình Định',id : 8},
    { label: 'Bình Dương',id : 9},
    { label: 'Bình Phước',id : 10},
    { label: 'Bình Thuận',id : 11},
    { label: 'Cà Mau',id : 12},
    { label: 'Cần Thơ',id : 13},
    { label: 'Cao Bằng',id : 14},
    { label: 'Đà Nẵng',id : 15},
    { label: 'Đắk Lắk',id : 16},
    { label: 'Đắk Nông',id : 17},
    { label: 'Điện Biên',id : 18},
    { label: 'Đồng Nai',id : 19},
    { label: 'Đồng Tháp',id : 20},
    { label: 'Gia Lai',id : 21},
    { label: 'Hà Giang',id : 22},
    { label: 'Hà Nam',id : 23},
    { label: 'Hà Nội',id : 24},
    { label: 'Hà Tĩnh',id : 25},
    { label: 'Hải Dương',id : 26},
    { label: 'Hải Phòng',id : 27},
    { label: 'Hậu Giang',id : 28},
    { label: 'Hòa Bình',id : 29},
    { label: 'Hưng Yên',id : 30},
    { label: 'Khánh Hòa',id : 31},
    { label: 'Kiên Giang',id : 32},
    { label: 'Kon Tum',id : 33},
    { label: 'Lai Châu',id : 34},
    { label: 'Lâm Đồng',id : 35},
    { label: 'Lạng Sơn',id : 36},
    { label: 'Lào Cai',id : 37},
    { label: 'Long An',id : 38},
    { label: 'Nam Định',id : 39},
    { label: 'Nghệ An',id : 40},
    { label: 'Ninh Bình',id : 41},
    { label: 'Ninh Thuận',id : 42},
    { label: 'Phú Thọ',id : 43},
    { label: 'Phú Yên',id : 44},
    { label: 'Quảng Bình',id : 45},
    { label: 'Quảng Nam',id : 46},
    { label: 'Quảng Ngãi',id : 47},
    { label: 'Quảng Ninh',id : 48},
    { label: 'Quảng Trị',id : 49},
    { label: 'Sóc Trăng',id : 50},
    { label: 'Sơn La',id : 51},
    { label: 'Tây Ninh',id : 52},
    { label: 'Thái Bình',id : 53},
    { label: 'Thái Nguyên',id : 54},
    { label: 'Thanh Hóa',id : 55},
    { label: 'Thừa Thiên Huế',id : 56},
    { label: 'Tiền Giang',id : 57},
    { label: 'Thành phố Hồ Chí Minh',id : 58},
    { label: 'Trà Vinh',id : 59},
    { label: 'Tuyên Quang',id : 60},
    { label: 'Vĩnh Long',id : 61},
    { label: 'Vĩnh Phúc',id : 62},
    { label: 'Yên Bái',id : 63},
    
  ];
  export const searchByMajor = [
    { label: 'Coke',id:1},
    { label: 'Fast food',id:2},
    { label: 'Car',id:3},
  ];
